# yaml-language-server: $schema=https://unpkg.com/@sveltia/cms/schema/sveltia-cms.json

backend:
  name: github
  repo: miyukowo/blog
  branch: main
  skip_ci: true

media_folder: /public/uploads
public_folder: /uploads

output:
  omit_empty_optional_fields: true

i18n:
  structure: multiple_folders
  locales: [en, vi]
  default_locale: en

collections:
  - name: posts
    label: Blog Posts
    label_singular: Post
    folder: /src/content/posts
    i18n: true
    create: true
    slug: "{{fields.translationKey}}"
    path: "{{fields.translationKey}}/index"
    extension: mdx
    format: frontmatter
    frontmatter_delimiter: "---"
    fields:
      - label: Title
        name: title
        widget: string
        i18n: true
        hint: "Tiêu đề của bài viết."

      - label: Description
        name: description
        widget: text
        i18n: true
        hint: "Mô tả của bài viết."

      - label: Publish Date
        name: pubDate
        widget: datetime
        date_format: YYYY-MM-DD
        time_format: false
        i18n: duplicate
        hint: "Ngày đăng của bài viết."

      - label: Updated Date
        name: updatedDate
        widget: datetime
        date_format: YYYY-MM-DD
        time_format: false
        required: false
        i18n: duplicate
        hint: "Ngày cập nhật bài viết."

      - label: Hero Image
        name: heroImage
        widget: image
        required: false
        i18n: duplicate
        hint: "Thêm ảnh hero."

      - label: Hero Image Alt
        name: heroImageAlt
        widget: string
        required: false
        i18n: true
        hint: "Thêm mô tả cho hình ảnh hero."

      - label: Tags
        name: tags
        widget: list
        required: false
        i18n: duplicate
        hint: "Gắn thẻ cho bài viết."

      - label: Categories
        name: categories
        widget: list
        required: false
        i18n: true
        hint: "Thêm chuyên mục cho bài viết."

      - label: Translation Key
        name: translationKey
        widget: string
        required: true
        i18n: duplicate
        hint: "Phải có gạch nối, dùng để kết nối bài viết EN ↔ VI với nhau."

      - label: Table of Contents
        name: toc
        widget: boolean
        default: true
        i18n: duplicate
        hint: "Bật tắt mục lục."

      - label: Pinned
        name: pinned
        widget: boolean
        default: false
        required: false
        i18n: duplicate
        hint: "Ghim bài viết lên đầu trang."

      - label: Draft
        name: draft
        widget: boolean
        default: false
        required: false
        i18n: duplicate
        hint: "Giữ bài viết thành bản thảo. Bài viết sẽ không hiển thị trên trang."

      - label: Comments
        name: comments
        widget: boolean
        default: true
        required: true
        i18n: duplicate
        hint: "Bật tắt chức năng bình luận."

      - label: Math (KaTeX)
        name: math
        widget: boolean
        default: false
        required: false
        i18n: duplicate
        hint: "Bật tắt chức năng diễn giải công thức toán học bằng KaTeX."

      - label: Unlisted
        name: unlisted
        widget: boolean
        default: false
        required: false
        i18n: duplicate
        hint: "Ẩn bài viết khỏi blog nhưng vẫn truy cập được nếu có liên kết trực tiếp."

      - label: Body
        name: body
        widget: markdown
        i18n: true
        hint: "Nội dung của bài viết."

  - name: pages
    label: Pages
    label_singular: Page
    folder: /src/content/pages
    i18n: true
    create: true
    slug: "{{slug}}"
    extension: md
    format: frontmatter
    fields:
      - { label: Title, name: title, widget: string, i18n: true }
      - { label: Description, name: description, widget: text, i18n: true }
      - label: Publish Date
        name: pubDate
        widget: datetime
        date_format: YYYY-MM-DD
        time_format: false
        required: false
        i18n: duplicate
      - label: Updated Date
        name: updatedDate
        widget: datetime
        date_format: YYYY-MM-DD
        time_format: false
        required: false
        i18n: duplicate
      - { label: Hero Image, name: heroImage, widget: image, required: false, i18n: duplicate }
      - { label: Hero Image Alt, name: heroImageAlt, widget: string, required: false, i18n: true }
      - { label: Show in Nav, name: showInNav, widget: boolean, default: false, i18n: duplicate }
      - { label: Table of Contents, name: toc, widget: boolean, default: true, i18n: duplicate }
      - { label: Comments, name: comments, widget: boolean, required: false, i18n: duplicate }
      - { label: Unlisted, name: unlisted, widget: boolean, default: false, i18n: duplicate }
      - { label: Canonical URL, name: canonicalURL, widget: string, required: false, i18n: duplicate }
      - { label: Body, name: body, widget: markdown, i18n: true }
      - { label: Translation Key, name: translationKey, widget: string, required: true, i18n: duplicate}